version: "3.9"

services:
  db:
    container_name: dwd_db
    image: postgres
    volumes:
      - dwd:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dwd
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    restart: unless-stopped

volumes:
  noc_v2: