version: "3.9"

services:
  db:
    container_name: wdd_db
    image: postgres
    volumes:
      - wdd:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=wdd
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    restart: unless-stopped

volumes:
  wdd: